title: Uditanshu Pandey
logo: imgs/Photo.png
description: Enthusiastic and dedicated, having expertise in Python, data structures, algorithms, and machine learning. Proficient with scikit-learn, tensorflow, numpy, and pandas. Experienced with natural language processing. Also preparing for the GATE exam to increase my technical knowledge. I am eager to contribute to unique projects and thrive in a dynamic enviroment.
show_downloads: true
theme: jekyll-theme-minimal
